name: 'GitHub Push - jcs'
description: 'Pushing to GitHub repository local changes'
author: 'Shen, Jen-Chieh'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{ github.token }}
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: true
    default: ${{ github.server_url }}
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
  rebase:
    description: 'Rebase before push'
    required: false
  force:
    description: 'Determines if force push is used'
    required: false
  tags:
    description: 'Determines if --tags is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
  retry:
    description: 'Retry attempts'
    required: false
    default: 1
runs:
  using: 'node20'
  main: 'start.js'
